# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('link', models.CharField(max_length=255, verbose_name='Əlaqəsi')),
                ('status', models.BooleanField(default=True, verbose_name='Saytda görünməsi')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Menular',
                'verbose_name': 'Menu',
                'ordering': ('id',),
            },
        ),
    ]
