# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import school.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slider başlığı')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontenti')),
                ('button', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to=school.options.tools.get_slider_photo_file_name)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Xeberin linki')),
                ('status', models.BooleanField(default=True, verbose_name='Saytda görünməsi')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
