# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Haqqımızda',
                'verbose_name': 'Haqqımızda',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('-id',), 'verbose_name': 'Slayd', 'verbose_name_plural': 'Slayder'},
        ),
    ]
