# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170414_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
