# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170414_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-id',), 'verbose_name': 'Məqalə', 'verbose_name_plural': 'Məqalələr'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ('id',), 'verbose_name': 'Bölmə', 'verbose_name_plural': 'Bölmələr'},
        ),
        migrations.AlterField(
            model_name='news',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Sections', verbose_name='Əlaqədə olduğu bölmə'),
        ),
    ]
