# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_about_us_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.News')),
            ],
            options={
                'verbose_name': 'Proqram',
                'verbose_name_plural': 'Proqramlar',
                'ordering': ('-id',),
            },
            bases=('website.news',),
        ),
    ]
