# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='relation',
        ),
    ]
