# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 00:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import school.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_news_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Soyad')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=school.options.tools.get_user_profile_photo_file_name)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Sayta görünüşü')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Multimediya',
                'verbose_name_plural': 'Multimediya',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlığı')),
                ('about', models.CharField(blank=True, max_length=255, null=True, verbose_name='Haqqında')),
                ('phone_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon nömrəsi 1')),
                ('phone_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon nömrəsi 2')),
                ('phone_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon nömrəsi 3')),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 1')),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2')),
                ('email_3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 3')),
            ],
            options={
                'verbose_name': 'Bizimlə Əlaqə',
                'verbose_name_plural': 'Bizimlə Əlaqə',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.News')),
            ],
            options={
                'verbose_name': 'Tədbir',
                'verbose_name_plural': 'Tədbirlər',
                'ordering': ('-id',),
            },
            bases=('website.news',),
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.News')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Videonun linki')),
            ],
            options={
                'verbose_name': 'Multimediya',
                'verbose_name_plural': 'Multimediya',
                'ordering': ('-id',),
            },
            bases=('website.news',),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=school.options.tools.get_news_photo_file_name, verbose_name='Örtük şəkli'),
        ),
    ]
