# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170416_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vakansiya ərazi',
                'verbose_name_plural': 'Vakansiya ərazilər',
                'ordering': ('-id',),
            },
        ),
    ]
