# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_vacancymenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.News')),
            ],
            options={
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ('id',),
                'verbose_name': 'Vakansiya',
            },
            bases=('website.news',),
        ),
        migrations.AlterModelOptions(
            name='vacancymenu',
            options={'ordering': ('id',), 'verbose_name': 'Vakansiya ərazi', 'verbose_name_plural': 'Vakansiya ərazilər'},
        ),
    ]
