# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 09:14
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Tələb olunur. 75 simvol və ya az. Hərflər, Rəqəmlər və @/./+/-/_ simvollar.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Düzgün istifadəçi adı daxil edin.', 'yanlışdır')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ad günü')),
                ('gender', models.IntegerField(choices=[(1, 'Kişi'), (2, 'Qadın')], verbose_name='cinsi')),
                ('unvani', models.CharField(max_length=255, verbose_name='ünvanı')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefonu')),
                ('study', models.CharField(blank=True, max_length=200, null=True, verbose_name='Təhsili')),
                ('position', models.IntegerField(blank=True, choices=[(1, 'Fənn Müəllimi'), (2, 'Ibtidai sinif Müəllimi')], null=True, verbose_name='Vəzifəsi')),
                ('usertype', models.IntegerField(choices=[(1, 'Müəllim'), (2, 'Menecer'), (3, 'Administrator')], verbose_name='Sistemdəki statusu')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Studend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('father_name', models.CharField(max_length=100, verbose_name='ata adı')),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Doğum tarixi')),
                ('gender', models.IntegerField(choices=[(1, 'Kişi'), (2, 'Qadın')], verbose_name='cinsi')),
                ('unvani', models.CharField(max_length=255, verbose_name='ünvanı')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefonu')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
