# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Kişi'), (2, 'Qadın')], null=True, verbose_name='cinsi'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefonu'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='unvani',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ünvanı'),
        ),
    ]
