# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170306_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='usertype',
            field=models.IntegerField(blank=True, choices=[(1, 'Müəllim'), (2, 'Menecer'), (3, 'Administrator')], null=True, verbose_name='Sistemdəki statusu'),
        ),
    ]
