# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_adminpanelurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
