# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_allowedipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedipaddress',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='allowedipaddress',
            name='ip',
            field=models.CharField(max_length=255),
        ),
    ]
