# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20170309_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studend',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Doğum tarixi'),
        ),
    ]
