# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import school.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20170310_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedipaddress',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=school.options.tools.get_user_profile_photo_file_name),
        ),
    ]
