# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20170329_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Gecikir'), (2, 'Normal'), (3, 'Vaxtinda')], default=0),
        ),
    ]
