# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20170405_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_student',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
