# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20170405_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='studend',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qeydiyyat vaxtı'),
        ),
    ]
