# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20170407_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='PandaBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filialın adı')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': 'Şöbə',
                'verbose_name_plural': 'Şöbələr',
            },
        ),
    ]
