# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_studend_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qalan_plan',
            field=models.IntegerField(default=0),
        ),
    ]
