# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20170408_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studend',
            name='father_name',
        ),
    ]
