# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_remove_studend_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prize', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Studend')),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-id',), 'verbose_name': 'Ödəniş cədvəli'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='qalan_plan',
            field=models.IntegerField(default=0, verbose_name='Qalan dərs sayı'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Gecikir'), (2, 'Normal'), (3, 'Vaxtinda')], default=0, verbose_name='Ödəniş statusuna'),
        ),
    ]
