# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20170409_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ('-id',), 'verbose_name': 'Əməliyyatlar', 'verbose_name_plural': 'Əməliyyatlar'},
        ),
        migrations.AddField(
            model_name='attendense',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendense',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'plus'), (2, 'minus'), (3, 'icazəli')], null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ödəniş vaxtı'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='prize',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qiymət (azn ilə)'),
        ),
    ]
