# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20170410_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-id',), 'verbose_name': 'Müəllim', 'verbose_name_plural': 'Müəllimlər'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Subject', verbose_name='Keçdiyi fənn'),
        ),
        migrations.AlterField(
            model_name='attendense',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='iştirak etdiyi gün'),
        ),
    ]
