# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20170412_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpanelurl',
            options={'verbose_name': 'Lazimsiz', 'verbose_name_plural': 'Lazimsiz'},
        ),
        migrations.AlterModelOptions(
            name='allowedipaddress',
            options={'ordering': ('-id',), 'verbose_name': 'İcazə verilmiş cihazlar', 'verbose_name_plural': 'Təhlükəsizlik'},
        ),
        migrations.AlterModelOptions(
            name='attendense',
            options={'verbose_name': 'Davamiyyət cədvəli', 'verbose_name_plural': 'Davamiyyət cədvəli'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'İstifadəçi', 'verbose_name_plural': 'İstifadəçilər'},
        ),
        migrations.AlterModelOptions(
            name='relationdatelesson',
            options={'verbose_name': 'Dərs', 'verbose_name_plural': 'Dərslər'},
        ),
        migrations.AlterModelOptions(
            name='studend',
            options={'verbose_name': 'Tələbə', 'verbose_name_plural': 'Tələbələr'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fənn', 'verbose_name_plural': 'Fənnlər'},
        ),
        migrations.AlterModelOptions(
            name='teacher_lesson',
            options={'verbose_name': 'Müəllimin dərsi', 'verbose_name_plural': 'Müəllimin dərsləri'},
        ),
        migrations.AlterModelOptions(
            name='teacher_student',
            options={'verbose_name': 'Müəllimin şagirdi', 'verbose_name_plural': 'Müəllimin şagirdi'},
        ),
    ]
