# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20170414_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandabranch',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
