# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_pandabranch_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandabranch',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Sistemdə görünməyi'),
        ),
    ]
