# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_auto_20170430_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='studend',
            name='money',
            field=models.FloatField(blank=True, null=True, verbose_name='Aylıq pulu'),
        ),
        migrations.AddField(
            model_name='studend',
            name='qalan_ders',
            field=models.IntegerField(default=0, verbose_name='Qalan dərs sayı'),
        ),
    ]
