# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_auto_20170430_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.FloatField(default=0, verbose_name='Istisna olan qiymət')),
                ('subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subject')),
            ],
        ),
    ]
