# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_studend_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studend',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Kişi'), (2, 'Qadın')], null=True, verbose_name='cinsi'),
        ),
        migrations.AlterField(
            model_name='studend',
            name='groups',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qrupun adı'),
        ),
        migrations.AlterField(
            model_name='studend',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefonu'),
        ),
        migrations.AlterField(
            model_name='studend',
            name='unvani',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ünvanı'),
        ),
    ]
