# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_auto_20170501_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentexception',
            options={'ordering': ('-id',), 'verbose_name': 'Maaşın hesablanmasında istisna', 'verbose_name_plural': 'Maaşın hesablanmasında istisnalar'},
        ),
        migrations.AlterField(
            model_name='paymentexception',
            name='prize',
            field=models.FloatField(default=0, verbose_name='Qiymət'),
        ),
        migrations.AlterField(
            model_name='paymentexception',
            name='subj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subject', verbose_name='Fənnin adı'),
        ),
    ]
