# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_auto_20170506_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studend',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Tam adi'),
        ),
    ]
