# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_auto_20170510_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentexception',
            name='filyal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.PandaBranch', verbose_name='Filial'),
        ),
    ]
