# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_deletedstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedstudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='DeletedStudent',
        ),
    ]
