# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_auto_20170514_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='studend',
            name='deleted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studend',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
