# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_auto_20170514_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='studend',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
