# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_studend_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendense',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'plus'), (2, 'minus'), (3, 'icazəli'), (4, 'çıxıb')], null=True),
        ),
    ]
