# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_auto_20170521_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='studend',
            name='cixdigi_zaman',
            field=models.CharField(default='', max_length=100),
        ),
    ]
