# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_studend_cixdigi_zaman'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='')),
                ('month', models.CharField(max_length=255)),
                ('teach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Arxiv Jurnallar',
                'ordering': ('-id',),
                'verbose_name': 'Arxiv Jurnal',
            },
        ),
    ]
