# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_jurnalarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tarix_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jurnalarchive',
            name='month',
            field=models.CharField(max_length=255, verbose_name='Ayliq Tarix'),
        ),
    ]
