# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_auto_20170611_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tarix_count',
        ),
        migrations.AddField(
            model_name='myuser',
            name='branch_status',
            field=models.BooleanField(default=False, verbose_name='Yalniz bir filiali gore biler'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.PandaBranch', verbose_name='Filial'),
        ),
    ]
