# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_auto_20170616_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandabranch',
            name='other',
            field=models.BooleanField(default=False, verbose_name='Tamamilə yeni bir sistemdir'),
        ),
    ]
