# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_auto_20170617_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandabranch',
            name='admin_color',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Rəngin kodu'),
        ),
    ]
