# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import school.options.tools


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_auto_20170617_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandabranch',
            name='admin_logo',
            field=models.ImageField(blank=True, null=True, upload_to=school.options.tools.get_admin_panel_logos, verbose_name='Admin panelin Logosu'),
        ),
    ]
